# Generated by Django 4.0.3 on 2022-05-01 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('event', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enchantment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('level', models.IntegerField()),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Graffiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('isAnimated', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('isModer', models.BooleanField()),
                ('isBanned', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('rarity', models.CharField(choices=[('SE', 'Select Edition'), ('DE', 'Deluxe Edition'), ('PE', 'Premium Edition'), ('XE', 'Exclusive Edition')], max_length=2)),
                ('enchantment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enchantment')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gun')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('skins', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visitor')),
            ],
        ),
    ]
