# Generated by Django 2.0 on 2022-05-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220503_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='isBanned',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='isModer',
            field=models.NullBooleanField(),
        ),
    ]
