# Generated by Django 4.0.4 on 2022-05-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_id_alter_charm_id_alter_enchantment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='wishlist',
        ),
    ]
