# Generated by Django 4.0.4 on 2022-05-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_visitor_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='gun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guns', to='api.gun'),
        ),
    ]
