# Generated by Django 4.0.4 on 2022-05-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_skin_gun'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='enchantment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enchantment'),
        ),
        migrations.AddField(
            model_name='graffiti',
            name='enchantment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enchantment'),
        ),
    ]
