# Generated by Django 4.0.4 on 2022-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_charm_enchantment_graffiti_enchantment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
